version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbpass123
      MYSQL_DATABASE: database
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:dbpass123@mysql:3306/database
    restart: always

volumes:
  mysql-data:
